### ISSUE TITLE
Repo does not work

### ISSUE THREAD

**Issue by sammo3182** [tcgriffith/xaringan_gh#1]
Thank you for making this repo. However, its seems not working for me. I followed your repo structure [here](https://github.com/sammo3182/slides_gh). But when I try to browse the URL, I got a 404. Any idea what wrong did I do? Thank you,

**Comment by tcgriffith** [comment]
![screenshot_20171203-081046](https://user-images.githubusercontent.com/19829201/33520181-8a321444-d801-11e7-8aae-76b7970766d1.png)

your repo looks fine to me. maybe the issue lies in the gh page setting?

**Comment by sammo3182** [comment]
Aha! You are right. Once I made the change. The slides appeared well. Thank you so much!!

Could I ask some basic questions, though? Do I have to use this `doc/slides` structure to host the Github page? I know `docs` folder is necessary. But if I move the xaringen slides out of slides folder, the slides seems failed.
Also, when you specified the slides link in the `index.html`,  it is `/xaringan_gh/slides/xaringan_example.html`. Why is there no "doc/" before "slides/", even if the slides folder is under docs?

Thank you,

**Comment by tcgriffith** [comment]
you need to understand website file structure and relative path first.
in gh page settings, you choose the root folder. it can be /docs/, the repo itself, or a new branch called gh_pages.
this root path has a index.html, which is displayed as you visit the site.

In the above settings, you can see that 
>your GitHub Pages is currently being built from the /docs folder in the master branch.

This means that:

gh pages treats docs folder as the root folder for the web page.
That is, `https://tcgriffith.github.io/xaringan_gh/` is actually mapped to `https://github.com/tcgriffith/xaringan_gh/docs/`

when you visit https://tcgriffith.github.io/xaringan_gh/, it's showing
https://github.com/tcgriffith/xaringan_gh/docs/index.html,

**Comment by sammo3182** [comment]
Got it! Thank you for the explanation and this great repo on hosting gh-pages!
